services:
  backend:
    build:
      context: ./groovegarden-backend
      dockerfile: Dockerfile
    env_file: 
      - ./groovegarden-backend/.env
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URL=http://localhost:${SERVER_PORT:-8081}/google/callback
      - SERVER_PORT=${SERVER_PORT:-8081}
      - FRONTEND_URL=http://localhost:${FLUTTER_PORT:-54321}
    ports:
      - "${SERVER_PORT:-8081}:${SERVER_PORT:-8081}"
    volumes:
      - backend-uploads:/app/uploads
    depends_on:
      - icecast
    restart: unless-stopped

  icecast:
    image: tlan16/icecast
    ports:
      - "${ICECAST_PORT:-9000}:${ICECAST_PORT:-9000}"
    volumes:
      - ./config/icecast.xml:/etc/icecast2/icecast.xml
      - backend-uploads:/uploads # Serve the same uploads directory for streaming
    restart: unless-stopped

  flutter:
    build:
      context: ./groovegarden_flutter
      dockerfile: Dockerfile
    ports:
      - "${FLUTTER_PORT:-54321}:${FLUTTER_PORT:-54321}"
    environment:
      - FLUTTER_PORT=${FLUTTER_PORT:-54321}
      - BACKEND_URL=http://backend:${SERVER_PORT:-8081}
    volumes:
      - ./groovegarden_flutter:/app
    command: >
      sh -c "flutter run -d web-server --web-port=${FLUTTER_PORT:-54321} --web-hostname=0.0.0.0"
    restart: unless-stopped

volumes:
  backend-uploads: