services:
  backend:
    build:
      context: ./groovegarden-backend
      dockerfile: Dockerfile
    env_file: 
      - ./groovegarden-backend/.env
    ports:
      - "${SERVER_PORT:-8081}:${SERVER_PORT:-8081}"
    volumes:
      - backend-uploads:/app/uploads
    depends_on:
      - icecast
    restart: unless-stopped

  icecast:
    image: tlan16/icecast
    ports:
      - "${ICECAST_PORT:-9000}:${ICECAST_PORT:-9000}"
    volumes:
      - ./config/icecast.xml:/etc/icecast2/icecast.xml
      - backend-uploads:/uploads # Serve the same uploads directory for streaming
    restart: unless-stopped

  flutter:
    build:
      context: ./groovegarden_flutter
      dockerfile: Dockerfile
    ports:
      - "${FLUTTER_PORT:-60387}:${FLUTTER_PORT:-60387}"
    volumes:
      - ./groovegarden_flutter:/app
    working_dir: /frontend-app
    command: ["flutter", "run", "--web-port", "${FLUTTER_PORT:-60387}"]
    restart: unless-stopped

volumes:
  backend-uploads: