name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # Specify the Flutter version you need

      - name: Install dependencies
        run: flutter pub get
        working-directory: groovegarden_flutter

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
      #   working-directory: groovegarden_flutter

      - name: Analyze project source
        run: flutter analyze
        working-directory: groovegarden_flutter

      - name: Run tests
        run: flutter test
        working-directory: groovegarden_flutter
