name: discord-webhook

on: [push, pull_request, workflow_dispatch]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: 'https://discord.com/api/webhooks/1346063234968457256/hd0iQOcaZJ4Bw5JD6oivV5hJ4FL8HgYa9L07Ab3U4Jz-DRB8fmi_utJ4cN87pfJv6xDD'
          content: 'A new push or pull request has been made.'
          wait: true
          username: 'GitHub Actions'
          avatar-url: 'https://example.com/custom-avatar.png'
          tts: false
          embed-title: 'GitHub Notification'
          embed-url: 'https://github.com/loonix/groovegarden'
          embed-description: 'A new update has been pushed to the repository.'
          embed-timestamp: "${{ github.event.head_commit.timestamp != '' && github.event.head_commit.timestamp || github.event.repository.updated_at }}"
          embed-color: '#FF0000'
          embed-footer-text: 'GitHub Actions'
          embed-footer-icon-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          embed-author-name: 'GitHub'
          embed-author-url: 'https://github.com'
          embed-author-icon-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
