name: discord-webhook

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: 'https://discord.com/api/webhooks/1346063234968457256/hd0iQOcaZJ4Bw5JD6oivV5hJ4FL8HgYa9L07Ab3U4Jz-DRB8fmi_utJ4cN87pfJv6xDD'
          # repo_name: # optional
          # censor_username: # optional
          # hide_links: # optional
          # color: # optional, default is 7dbbe6
